WebApp/Models/Car.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models
{
    public class Car
    {
        public Guid Id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Car Name is required.")]
        [RegularExpression(@"^\w[\w\s]{0,254}\w$", ErrorMessage = "Car Name should have a length from 2 to 256 symbols without wrapping by spaces.")]
        [Display(Name = "Car Name")]
        public string Name { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Year is required.")]
        public int Year { get; set; }

        [EnumDataType(typeof(CarProducersEnum))]
        public CarProducersEnum Producer { get; set; }
    }
}

WebApp/Models/CarProducersEnum.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public enum CarProducersEnum
    {
        [Display(Name = "Enum Vw")]
        EnumVw = 10, 

        [Display(Name = "Audi")]
        Audi = 20, 

        [Display(Name = "Alfa Romeo")]
        AlfaRomeo = 30
    }
}

WebApp/Models/ErrorViewModel.cs
using System;

namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Controllers/CarsController.cs
using System;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using WebApp.Assets.Mediator.CreatingCar;
using WebApp.Assets.Mediator.DeletingCar;
using WebApp.Assets.Mediator.GettingCarById;
using WebApp.Assets.Mediator.GettingNotDeletedCarsList;
using WebApp.Assets.Mediator.UpdatingCar;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class CarsController : Controller
    {
        readonly IMediator _mediator;

        public CarsController(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<ActionResult> Index()
        {
            var request = new GetNotDeletedCarsListRequest();
            var model = await _mediator.Send(request);

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Car newCar)
        {
            var createCarRequest = new CreateCarRequest
            {
                CarPrototype = newCar
            };

            await _mediator.Send(createCarRequest);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<ActionResult> Edit(Guid carId)
        {
            var request = new GetCarByIdRequest {CarId = carId};
            var model = await _mediator.Send(request);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit([FromForm] Car updatedCar)
        {
            var request = new UpdateCarRequest {CarNewVersion = updatedCar};
            await _mediator.Send(request);
            
            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> Delete(Guid carId)
        {
            var request = new DeleteCarRequest {CarId = carId};
            await _mediator.Send(request);

            return RedirectToAction("Index");
        }
    }
}

WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Views/Cars/CarPartial.cshtml
@using Microsoft.AspNetCore.Razor.TagHelpers
@model Car

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class="form-control" }})
    @Html.ValidationMessageFor(model => model.Name, null, new { @class= "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Description)
    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.Description, null, new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Year)
    @Html.EditorFor(model => model.Year, new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessageFor(model => model.Year, null, new { @class = "text-danger" })
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Producer)
    @Html.DropDownList("Producer", Html.GetEnumSelectList<CarProducersEnum>(), "Select", new {@class = "form-control"})
</div>

WebApp/Views/Cars/Create.cshtml
@model WebApp.Models.Car

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Create", "Cars", FormMethod.Post))
        {
            await Html.RenderPartialAsync("CarPartial", new Car());
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
    @Html.ActionLink("Back to Cars List", "Index")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Cars/Edit.cshtml
@model WebApp.Models.Car

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        @using (Html.BeginForm("Edit", "Cars", null, FormMethod.Post))
        {
            @Html.HiddenFor(model => model.Id)
            await Html.RenderPartialAsync("CarPartial", Model);
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div>
    @Html.ActionLink("Back to Cars List", "Index")
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Cars/Index.cshtml
@model IEnumerable<WebApp.Models.Car>

@{
    ViewData["Title"] = "Cars List";
}

<h1>Cars List</h1>

<p>
    @Html.ActionLink("Register New Car", "Create")
</p>
<table class="table">
    <thead>
        <tr>
            <th class="car-name-table-column">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th class="car-year-table-column">
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th class="car-producer-table-column">
                @Html.DisplayNameFor(model => model.Producer)
            </th>
            <th class="actions-table-column"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var car in Model.OrderBy(c => c.Year))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => car.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => car.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => car.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => car.Producer)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { carId = car.Id }) |
                    <button type="button" class="btn btn-danger btn-sm" data-href="@Url.Action("Delete", new { carId= car.Id})" data-toggle="modal" data-target="#deleteConfirmationModal">Delete</button>

                    @*@Html.ActionLink("Delete", "Delete", new { carId = car.Id })*@
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="deleteConfirmationModal">
    <div class="modal-dialog modal-confirm">
        <div class="modal-content">
            <div class="modal-header flex-column">
                <div class="delete-icon-box">
                    <img src="~/delete.png" alt="Deleting Item" />
                </div>
                <h4 class="modal-title w-100">Are you sure?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="True">&times;</button>
            </div>
            <div class="modal-body">
                <p>Operation can't be undone. Are you sure?</p>
            </div>
            <div class="modal-footer justify-content-center">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <a class="btn btn-danger" id="runDelete">Delete</a>
            </div>
        </div>
    </div>
</div>
<!-- EndModal -->

@section Scripts
{
    <script type="text/javascript">
        $(function() {
            $('#deleteConfirmationModal').on('show.bs.modal', function (e) {
                $(this).find('#runDelete').attr('href', $(e.relatedTarget).data('href'));
            });
        });
    </script>
}

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is the test application created for Pitney Bowes to demonstrate what do I know about ASP.NET Core MVC. :-)</p>
    <span>Hope you'll like it.</span>
</div>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="~/favicon.ico" />
    <title>Cars - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.min.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        @Html.ActionLink("Cars", "Index", "Cars", null, new {@class="nav-link text-dark"})
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Home", "Index", "Home", null, new {@class="nav-link text-dark"})
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - Cars Catalogue. Denys Chuiko
    </div>
</footer>
<script src="~/js/site.min.js"></script>
@RenderSection("Scripts", required: false)
</body>
</html>